from __future__ import annotations

import json
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path


STATE_ROOT = Path(__file__).resolve().parents[2] / "processed" / "pipeline_state"

STEP_DEFINITIONS = [
    {
        "key": "import_dicom",
        "step_name": "import DICOM",
        "input_expected": "Raw DICOM study folders",
        "output_expected": "Catalog entry and raw DICOM paths in DB",
    },
    {
        "key": "select_core_sequences",
        "step_name": "selezione/core delle sequenze",
        "input_expected": "Detected DICOM series",
        "output_expected": "Selected core sequences (T1/T1ce/T2/FLAIR)",
    },
    {
        "key": "initial_validation",
        "step_name": "FeTS initial validation",
        "input_expected": "Selected DICOM core sequences",
        "output_expected": "Validated FeTS-ready case structure",
    },
    {
        "key": "nifti_conversion",
        "step_name": "DICOM to NIfTI",
        "input_expected": "Validated FeTS-ready DICOM case",
        "output_expected": "Core NIfTI volumes generated by FeTS",
    },
    {
        "key": "brain_extraction",
        "step_name": "brain extraction",
        "input_expected": "FeTS-converted NIfTI volumes",
        "output_expected": "Brain-extracted NIfTI volumes",
    },
    {
        "key": "tumor_segmentation",
        "step_name": "tumor segmentation",
        "input_expected": "Brain-extracted volumes",
        "output_expected": "Tumor mask NIfTI output",
    },
]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def state_path(subject_id: str, session_label: str) -> Path:
    return STATE_ROOT / subject_id / f"{session_label}.json"


def _default_steps() -> list[dict]:
    steps = []
    for step in STEP_DEFINITIONS:
        steps.append(
            {
                "key": step["key"],
                "step_name": step["step_name"],
                "input_expected": step["input_expected"],
                "output_expected": step["output_expected"],
                "status": "pending",
                "output_path": None,
                "error_message": None,
                "started_at": None,
                "finished_at": None,
            }
        )
    return steps


def _default_state(subject_id: str, session_label: str, *, session_id: int | None = None, dataset: str | None = None) -> dict:
    return {
        "subject_id": subject_id,
        "session_label": session_label,
        "session_id": session_id,
        "dataset": dataset,
        "state_path": str(state_path(subject_id, session_label)),
        "updated_at": now_iso(),
        "steps": _default_steps(),
    }


def load_state(subject_id: str, session_label: str) -> dict:
    path = state_path(subject_id, session_label)
    if not path.exists():
        return _default_state(subject_id, session_label)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return _default_state(subject_id, session_label)

    steps_by_key = {step["key"]: deepcopy(step) for step in data.get("steps", []) if step.get("key")}
    steps = []
    for step in STEP_DEFINITIONS:
        current = steps_by_key.get(step["key"], {})
        steps.append(
            {
                "key": step["key"],
                "step_name": step["step_name"],
                "input_expected": step["input_expected"],
                "output_expected": step["output_expected"],
                "status": current.get("status", "pending"),
                "output_path": current.get("output_path"),
                "error_message": current.get("error_message"),
                "started_at": current.get("started_at"),
                "finished_at": current.get("finished_at"),
            }
        )
    return {
        "subject_id": data.get("subject_id", subject_id),
        "session_label": data.get("session_label", session_label),
        "session_id": data.get("session_id"),
        "dataset": data.get("dataset"),
        "state_path": str(path),
        "updated_at": data.get("updated_at"),
        "steps": steps,
    }


def save_state(subject_id: str, session_label: str, state: dict) -> dict:
    path = state_path(subject_id, session_label)
    path.parent.mkdir(parents=True, exist_ok=True)
    state["subject_id"] = subject_id
    state["session_label"] = session_label
    state["state_path"] = str(path)
    state["updated_at"] = now_iso()
    path.write_text(json.dumps(state, ensure_ascii=True, indent=2), encoding="utf-8")
    return state


def ensure_state(subject_id: str, session_label: str, *, session_id: int | None = None, dataset: str | None = None) -> dict:
    state = load_state(subject_id, session_label)
    if session_id is not None:
        state["session_id"] = session_id
    if dataset is not None:
        state["dataset"] = dataset
    return save_state(subject_id, session_label, state)


def update_step(
    subject_id: str,
    session_label: str,
    step_key: str,
    *,
    status: str | None = None,
    output_path: str | None = None,
    error_message: str | None = None,
    started: bool = False,
    finished: bool = False,
    session_id: int | None = None,
    dataset: str | None = None,
) -> dict:
    state = ensure_state(subject_id, session_label, session_id=session_id, dataset=dataset)
    step = next((item for item in state["steps"] if item["key"] == step_key), None)
    if step is None:
        raise KeyError(f"Unknown pipeline step: {step_key}")
    if status is not None:
        step["status"] = status
    if output_path is not None:
        step["output_path"] = output_path
    if error_message is not None:
        step["error_message"] = error_message
    elif status in {"running", "done"}:
        step["error_message"] = None
    if started and not step.get("started_at"):
        step["started_at"] = now_iso()
    if finished:
        step["finished_at"] = now_iso()
    return save_state(subject_id, session_label, state)


def reset_downstream_steps(subject_id: str, session_label: str, step_keys: list[str]) -> dict:
    state = ensure_state(subject_id, session_label)
    step_key_set = set(step_keys)
    for step in state["steps"]:
        if step["key"] not in step_key_set:
            continue
        step["status"] = "pending"
        step["output_path"] = None
        step["error_message"] = None
        step["started_at"] = None
        step["finished_at"] = None
    return save_state(subject_id, session_label, state)


def set_current_step_failed(
    subject_id: str,
    session_label: str,
    step_key: str,
    *,
    error_message: str,
    output_path: str | None = None,
) -> dict:
    return update_step(
        subject_id,
        session_label,
        step_key,
        status="failed",
        output_path=output_path,
        error_message=error_message,
        started=True,
        finished=True,
    )


def pipeline_state_summary(state: dict | None) -> dict:
    if not state:
        return {"last_done": None, "failed": None, "running": None}
    summary = {"last_done": None, "failed": None, "running": None}
    for step in state.get("steps", []):
        if step["status"] == "done":
            summary["last_done"] = step["step_name"]
        if step["status"] == "running":
            summary["running"] = step["step_name"]
        if step["status"] == "failed":
            summary["failed"] = step["step_name"]
    return summary
