from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timezone

from app.db import db


@contextmanager
def _use_conn(conn=None):
    """Yields the provided connection or opens a new one."""
    if conn is not None:
        yield conn
    else:
        with db() as c:
            yield c


STEP_DEFINITIONS = [
    {
        "key": "import_dicom",
        "step_name": "import DICOM",
        "phase": "import",
        "input_expected": "Raw DICOM study folders",
        "output_expected": "Catalog entry and raw DICOM paths in DB",
    },
    {
        "key": "select_core_sequences",
        "step_name": "selezione sequenze core",
        "phase": "import",
        "input_expected": "Detected DICOM series",
        "output_expected": "Selected core sequences (T1/T1ce/T2/FLAIR)",
    },
    {
        "key": "initial_validation",
        "step_name": "FeTS initial validation",
        "phase": "preprocessing",
        "input_expected": "Selected DICOM core sequences",
        "output_expected": "Validated FeTS-ready case structure",
    },
    {
        "key": "nifti_conversion",
        "step_name": "DICOM to NIfTI",
        "phase": "preprocessing",
        "input_expected": "Validated FeTS-ready DICOM case",
        "output_expected": "Core NIfTI volumes generated by FeTS",
    },
    {
        "key": "brain_extraction",
        "step_name": "brain extraction",
        "phase": "preprocessing",
        "input_expected": "FeTS-converted NIfTI volumes",
        "output_expected": "Brain-extracted NIfTI volumes",
    },
    {
        "key": "tumor_segmentation",
        "step_name": "tumor segmentation",
        "phase": "segmentation",
        "input_expected": "Brain-extracted volumes",
        "output_expected": "Tumor mask NIfTI output",
    },
    {
        "key": "segmentation_done",
        "step_name": "segmentation completed",
        "phase": "segmentation",
        "input_expected": "Tumor mask NIfTI output",
        "output_expected": "Segmentation finalized and registered in DB",
    },
    {
        "key": "analysis_available",
        "step_name": "analysis available",
        "phase": "analysis",
        "input_expected": "Completed segmentation",
        "output_expected": "Metrics and longitudinal analysis available",
    },
    {
        "key": "export_done",
        "step_name": "export completed",
        "phase": "export",
        "input_expected": "Finalized structures",
        "output_expected": "DICOM RTSTRUCT exported on native series",
    },
]

_STEP_META = {s["key"]: s for s in STEP_DEFINITIONS}

PHASES = ["import", "preprocessing", "segmentation", "analysis", "export"]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


# ── DB helpers ────────────────────────────────────────────────────────────────

def _resolve_session_id(conn, subject_id: str, session_label: str) -> int | None:
    row = conn.execute(
        """
        SELECT ses.id FROM sessions ses
        JOIN subjects sub ON sub.id = ses.subject_id
        WHERE sub.subject_id = ? AND ses.session_label = ?
        """,
        (subject_id, session_label),
    ).fetchone()
    return int(row[0]) if row else None


def _ensure_steps(conn, session_id: int) -> None:
    """Inserts missing checklist rows for a session (idempotent)."""
    existing = {
        row[0]
        for row in conn.execute(
            "SELECT step_key FROM session_checklist WHERE session_id = ?",
            (session_id,),
        ).fetchall()
    }
    ts = now_iso()
    for step in STEP_DEFINITIONS:
        if step["key"] not in existing:
            conn.execute(
                """
                INSERT INTO session_checklist
                    (session_id, phase, step_key, step_name, status, updated_at)
                VALUES (?, ?, ?, ?, 'pending', ?)
                """,
                (session_id, step["phase"], step["key"], step["step_name"], ts),
            )


def _build_state(conn, subject_id: str, session_label: str, session_id: int) -> dict:
    """Assembles the state dict from DB rows, preserving STEP_DEFINITIONS order."""
    rows = {
        row["step_key"]: row
        for row in conn.execute(
            """
            SELECT step_key, status, blocking_reason, output_ref, started_at, finished_at
            FROM session_checklist WHERE session_id = ?
            """,
            (session_id,),
        ).fetchall()
    }

    steps = []
    for s in STEP_DEFINITIONS:
        row = rows.get(s["key"])
        steps.append({
            "key":             s["key"],
            "step_name":       s["step_name"],
            "phase":           s["phase"],
            "input_expected":  s["input_expected"],
            "output_expected": s["output_expected"],
            "status":          row["status"]          if row else "pending",
            "output_path":     row["output_ref"]      if row else None,
            "error_message":   row["blocking_reason"] if row else None,
            "started_at":      row["started_at"]      if row else None,
            "finished_at":     row["finished_at"]     if row else None,
        })

    updated = conn.execute(
        "SELECT MAX(updated_at) FROM session_checklist WHERE session_id = ?",
        (session_id,),
    ).fetchone()[0]

    return {
        "subject_id":    subject_id,
        "session_label": session_label,
        "session_id":    session_id,
        "updated_at":    updated or now_iso(),
        "steps":         steps,
    }


def _default_state(subject_id: str, session_label: str, session_id: int | None = None) -> dict:
    """Returns an in-memory pending state when the session is not in the DB yet."""
    steps = [
        {
            "key":             s["key"],
            "step_name":       s["step_name"],
            "phase":           s["phase"],
            "input_expected":  s["input_expected"],
            "output_expected": s["output_expected"],
            "status":          "pending",
            "output_path":     None,
            "error_message":   None,
            "started_at":      None,
            "finished_at":     None,
        }
        for s in STEP_DEFINITIONS
    ]
    return {
        "subject_id":    subject_id,
        "session_label": session_label,
        "session_id":    session_id,
        "updated_at":    now_iso(),
        "steps":         steps,
    }


# ── Public interface (same as before) ─────────────────────────────────────────

def load_state(subject_id: str, session_label: str, *, conn=None) -> dict:
    with _use_conn(conn) as c:
        sid = _resolve_session_id(c, subject_id, session_label)
        if sid is None:
            return _default_state(subject_id, session_label)
        _ensure_steps(c, sid)
        return _build_state(c, subject_id, session_label, sid)


def save_state(subject_id: str, session_label: str, state: dict) -> dict:
    # DB writes happen in update_step / reset_downstream_steps.
    # Kept for interface compatibility with callers that still call this.
    return state


def ensure_state(
    subject_id: str,
    session_label: str,
    *,
    session_id: int | None = None,
    dataset: str | None = None,
    conn=None,
) -> dict:
    with _use_conn(conn) as c:
        sid = _resolve_session_id(c, subject_id, session_label) or session_id
        if sid is None:
            return _default_state(subject_id, session_label)
        _ensure_steps(c, sid)
        return _build_state(c, subject_id, session_label, sid)


def update_step(
    subject_id: str,
    session_label: str,
    step_key: str,
    *,
    status: str | None = None,
    output_path: str | None = None,
    error_message: str | None = None,
    started: bool = False,
    finished: bool = False,
    started_at_value: str | None = None,
    finished_at_value: str | None = None,
    session_id: int | None = None,
    dataset: str | None = None,
    conn=None,
) -> dict:
    if step_key not in _STEP_META:
        raise KeyError(f"Unknown pipeline step: {step_key}")

    with _use_conn(conn) as c:
        sid = _resolve_session_id(c, subject_id, session_label) or session_id
        if sid is None:
            return _default_state(subject_id, session_label)

        _ensure_steps(c, sid)

        row = c.execute(
            "SELECT started_at, finished_at FROM session_checklist WHERE session_id = ? AND step_key = ?",
            (sid, step_key),
        ).fetchone()

        sets, params = [], []

        if status is not None:
            sets.append("status = ?");          params.append(status)
        if output_path is not None:
            sets.append("output_ref = ?");      params.append(output_path)
        if error_message is not None:
            sets.append("blocking_reason = ?"); params.append(error_message)
        elif status in {"running", "done"}:
            sets.append("blocking_reason = NULL")

        if started and row and not row["started_at"]:
            sets.append("started_at = ?"); params.append(started_at_value or now_iso())
        if finished and row and not row["finished_at"]:
            sets.append("finished_at = ?"); params.append(finished_at_value or now_iso())

        sets.append("updated_at = ?"); params.append(now_iso())
        params += [sid, step_key]

        c.execute(
            f"UPDATE session_checklist SET {', '.join(sets)} WHERE session_id = ? AND step_key = ?",
            params,
        )
        return _build_state(c, subject_id, session_label, sid)


def reset_downstream_steps(subject_id: str, session_label: str, step_keys: list[str], *, conn=None) -> dict:
    with _use_conn(conn) as c:
        sid = _resolve_session_id(c, subject_id, session_label)
        if sid is None:
            return _default_state(subject_id, session_label)

        _ensure_steps(c, sid)
        ts = now_iso()
        for key in step_keys:
            c.execute(
                """
                UPDATE session_checklist
                SET status = 'pending', output_ref = NULL, blocking_reason = NULL,
                    started_at = NULL, finished_at = NULL, updated_at = ?
                WHERE session_id = ? AND step_key = ?
                """,
                (ts, sid, key),
            )
        return _build_state(c, subject_id, session_label, sid)


def set_current_step_failed(
    subject_id: str,
    session_label: str,
    step_key: str,
    *,
    error_message: str,
    output_path: str | None = None,
    conn=None,
) -> dict:
    return update_step(
        subject_id, session_label, step_key,
        status="failed",
        output_path=output_path,
        error_message=error_message,
        started=True,
        finished=True,
        conn=conn,
    )


def pipeline_state_summary(state: dict | None) -> dict:
    if not state:
        return {"last_done": None, "failed": None, "running": None}
    summary = {"last_done": None, "failed": None, "running": None}
    for step in state.get("steps", []):
        if step["status"] == "done":
            summary["last_done"] = step["step_name"]
        if step["status"] == "running":
            summary["running"] = step["step_name"]
        if step["status"] == "failed":
            summary["failed"] = step["step_name"]
    return summary


# ── Batch advancement query ───────────────────────────────────────────────────

def sessions_ready_for_phase(phase: str) -> list[dict]:
    """
    Returns sessions where the previous phase is fully done
    and the requested phase has not yet started (all steps pending).

    For 'import' (no previous phase) returns sessions with no import steps started.
    """
    if phase not in PHASES:
        raise ValueError(f"Unknown phase: {phase}. Valid: {PHASES}")

    phase_idx = PHASES.index(phase)

    with db() as conn:
        if phase_idx == 0:
            # import: no previous phase — return sessions with all import steps pending
            rows = conn.execute(
                """
                SELECT
                    ses.id AS session_id, ses.session_label,
                    sub.subject_id, sub.dataset
                FROM sessions ses
                JOIN subjects sub ON sub.id = ses.subject_id
                WHERE NOT EXISTS (
                    SELECT 1 FROM session_checklist sc
                    WHERE sc.session_id = ses.id
                      AND sc.phase = 'import'
                      AND sc.status != 'pending'
                )
                ORDER BY sub.subject_id, ses.session_label
                """
            ).fetchall()
        else:
            prev_phase = PHASES[phase_idx - 1]
            rows = conn.execute(
                """
                SELECT
                    ses.id AS session_id, ses.session_label,
                    sub.subject_id, sub.dataset
                FROM sessions ses
                JOIN subjects sub ON sub.id = ses.subject_id
                WHERE
                    -- previous phase fully done
                    EXISTS (
                        SELECT 1 FROM session_checklist sc
                        WHERE sc.session_id = ses.id AND sc.phase = ?
                          AND sc.status = 'done'
                    )
                    AND NOT EXISTS (
                        SELECT 1 FROM session_checklist sc
                        WHERE sc.session_id = ses.id AND sc.phase = ?
                          AND sc.status NOT IN ('pending', 'skipped')
                    )
                    -- current phase not yet started
                    AND NOT EXISTS (
                        SELECT 1 FROM session_checklist sc
                        WHERE sc.session_id = ses.id AND sc.phase = ?
                          AND sc.status NOT IN ('pending', 'skipped')
                    )
                ORDER BY sub.subject_id, ses.session_label
                """,
                (prev_phase, prev_phase, phase),
            ).fetchall()

    return [dict(r) for r in rows]
